#!/bin/bash
# Script to run various tests of the SEVIRI reader
# Simon Proud (simon.proud@physics.ox.ac.uk)
# These examples can be modified for your channels/data
# Note that currently the image segment / pixel to output
# are stored in the example_c_nat.c / example_c_hrit.c files
# To output a different pixel you must change the values and make


echo ""
echo "Test NAT with 0100 generation file (missing some bands)"
./example_c_nat /home/proud/Desktop/seviri_native_util/Test_Files/NAT/MSG1-SEVI-MSG15-0100-NA-20060303121241.nat 1101011001 1 0
echo "Test NAT with 0201 generation file"
./example_c_nat /home/proud/Desktop/seviri_native_util/Test_Files/NAT/MSG1-SEVI-MSG15-0201-NA-20060303121241.nat 1101011001 1 0
echo "Test HRIT"
./example_c_hrit /home/proud/Desktop/seviri_native_util/Test_Files/HRIT/ 200603031200 1 1101011001 1 0

echo ""
echo ""
echo ""
echo "Test NAT with 0100 generation file (missing some bands)"
./example_c_nat /home/proud/Desktop/seviri_native_util/Test_Files/NAT/MSG1-SEVI-MSG15-0100-NA-20060303121241.nat 1101011001 0 1
echo "Test NAT with 0201 generation file"
./example_c_nat /home/proud/Desktop/seviri_native_util/Test_Files/NAT/MSG1-SEVI-MSG15-0201-NA-20060303121241.nat 1101011001 0 1
echo "Test HRIT"
./example_c_hrit /home/proud/Desktop/seviri_native_util/Test_Files/HRIT/ 200603031200 1 1101011001 0 1

echo ""
echo ""
echo ""
echo "Test NAT with 0100 generation file (missing some bands)"
./example_c_nat /home/proud/Desktop/seviri_native_util/Test_Files/NAT/MSG1-SEVI-MSG15-0100-NA-20060303121241.nat 1101011001 2 0
echo "Test NAT with 0201 generation file"
./example_c_nat /home/proud/Desktop/seviri_native_util/Test_Files/NAT/MSG1-SEVI-MSG15-0201-NA-20060303121241.nat 1101011001 2 0
echo "Test HRIT"
./example_c_hrit /home/proud/Desktop/seviri_native_util/Test_Files/HRIT/ 200603031200 1 1101011001 2 0
